version: "3.7"
services:
  ngnix:
    build: 
        context: ./container/nginx
        dockerfile: ./Dockerfile
    ports:
     - "8080:80"
    volumes:
      - type: bind
        source: ./container/nginx/logs
        target: /var/logs/nginx
      - type: bind
        source: ./container/php-fpm/www
        target: /var/www
    links:
     - php-fpm
  php-fpm:
    build: 
        context: ./container/php-fpm
        dockerfile: ./Dockerfile
    deploy:
      replicas: 2
    volumes:
      - type: bind
        source: ./container/php-fpm/www
        target: /var/www
volumes:
  app_files:
