version: "2"

services:

  balancer:
    image: 'dockercloud/haproxy'
    links:
      - web
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:1936:1936'
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  web:
    build: 
        context: ./container/web
        dockerfile: ./Dockerfile
    links:
       - database
       - redis
       - session-storage
    volumes:
       - ./container/web/logs:/var/logs/nginx
       - ./application:/var/www

  session-storage:
    build:
        context: ./container/session-storage
        dockerfile: ./Dockerfile

  redis:
    build:
        context: ./container/redis
        dockerfile: ./Dockerfile

  database:
    build:
        context: ./container/database
        dockerfile: ./Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root

