version: "3.7"
services:
  ngnix:
    build: 
        context: ./container/nginx
        dockerfile: ./Dockerfile
    ports:
     - "8080-8081:80"
    volumes:
      - type: bind
        source: ./container/nginx/logs
        target: /var/logs/nginx
      - type: bind
        source: ./container/php/www
        target: /var/www
    links:
     - php
  php:
    build: 
        context: ./container/php
        dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./container/php/www
        target: /var/www
volumes:
  app_files:
