version: "2"

services:

  balancer:
    image: 'dockercloud/haproxy'
    links:
      - web
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:1936:1936'
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  web:
    build: 
        context: ./container/web
        dockerfile: ./Dockerfile
    volumes:
       - ./container/web/logs:/var/logs/nginx
       - ./application:/var/www

  session-storage:
    build:
        context: ./container/session-storage
        dockerfile: ./Dockerfile
